// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPaMl5DP8a8V-IgD11A0gRVSamFwNsqwM',
    appId: '1:434939847899:android:fc6c6d5f4b522ee6e1d8fe',
    messagingSenderId: '434939847899',
    projectId: 'flutter-web-rtc-c4539',
    storageBucket: 'flutter-web-rtc-c4539.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8M72okvAJsd-iZxBhsMSKsLCsRxGEf_U',
    appId: '1:434939847899:ios:1ef4c1a2d0ceae3de1d8fe',
    messagingSenderId: '434939847899',
    projectId: 'flutter-web-rtc-c4539',
    storageBucket: 'flutter-web-rtc-c4539.firebasestorage.app',
    iosBundleId: 'com.example.flutterWebRtc',
  );
}
